logging:
  level: DEBUG # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  output: BOTH # Options: STDOUT, FILE, BOTH
  logfile: game.log
  overwrite: true

hardware:
  robot:
    portwin: "COM5"  # or load from config
    portlinux: "/dev/ttyACM0"
    angles_file: "robot_arm/robot_angles.json"  # path relative to project root
    pause_between_moves: false
  arduino:
    portwin: "COM6"
    portlinux:  "/dev/pts/3" # "/dev/ttyUSB0" ] # try the virtual connection first, then the real one.
    baudrate: 115200
